### ISSUE TITLE
Toggles background

### ISSUE THREAD

**Issue by Kr1stat0s** [NoisyFlake/MagmaEvo-support#33] opened 2020-03-22 23:07 UTC
I installed version 1.2.2 and cannot get rid of the toggles background as seen in the below ss...
![89BED366-78E0-4244-92CB-461AA92288FF](https://user-images.githubusercontent.com/40151719/77263943-629b5600-6c67-11ea-80ec-6fb6189f3a68.png)
I downgraded to 1.2.1, resprung and the background “shadow” is gone as seen below...
![08831AC7-635C-48E1-A171-ED9BF24EFD77](https://user-images.githubusercontent.com/40151719/77264058-99716c00-6c67-11ea-9c83-1f289e77fd8a.png)
I did nothing other than upgrade and Respring then downgrade and Respring...did not change anything...
Upgraded back to 1.2.2 to mess with the settings but nothing took away the background...had to downgrade to 1.2.1 to get rid of it...

**Comment by gerbil-snot** [comment] 2020-03-23 15:14
Same issue, latest version breaks Gylph only

**Comment by NoisyFlake** [comment] 2020-03-23 19:43
Have you made sure to set the background color to transparent? It's no longer a toggle to hide the background, but a color picker where you have to select a transparent color in order to hide it (as explained in the update notes).

**Comment by Kr1stat0s** [comment] 2020-03-24 19:02
My mistake. I did make sure it was transparent and it almost all works. Please see below with all the backgrounds set to transparent. You can still a background under the Music icon. Version 1.2.2


Now please see below the background behind the Music icon. Version 1.2.1

**Comment by NoisyFlake** [comment] 2020-03-24 19:38
You haven't uploaded any images once again...

**Comment by Kr1stat0s** [comment] 2020-03-24 19:44
My mistake. I did make sure it was transparent and it almost all works. Please see below with all the backgrounds set to transparent. You can still a background under the Music icon. Version 1.2.2

![BA0031BE-2782-4771-BC72-053278979576](https://user-images.githubusercontent.com/40151719/77469922-d5c6d880-6ddd-11ea-96bb-f035774a96ff.png)


Now please see below the background behind the Music icon. Version 1.2.1

![47E42B6F-7500-463D-B9D7-0DD9F6E7630A](https://user-images.githubusercontent.com/40151719/77469954-e2e3c780-6ddd-11ea-83e3-29359019dd38.png)

**Comment by Kr1stat0s** [comment] 2020-03-24 20:44
I had sent them in a reply email and they didn’t post. I posted them just now directly in the github tweak page.

**Comment by NoisyFlake** [comment] 2020-03-25 12:48
This is a duplicate of #32

**Closed by NoisyFlake** 2020-03-25 12:48 UTC
