### ISSUE TITLE
Color on play/pause has the incorrect color. 

### ISSUE THREAD

**Issue by 9kag** [NoisyFlake/MagmaEvo-support#31] opened 2020-03-22 14:56 UTC
**Describe the bug**

The play/pause icon in the media settings has the incorrect color when no music is playing! 

**To Reproduce**
1. Change the colour of the play/pause and back/next
2. After you respring the next/back color will be the color of the play/pause icon. 

**Expected behavior**
The color should stay consistent when no music is playing and not use a different component color.

**Screenshots**

**iOS Version:** iOS 13.3

**Device:** iPhone X 

**Tweak list:**
Either attach it as a text file or put it on e.g. pastebin.com

**Additional context**

**Comment by NoisyFlake** [comment] 2020-03-23 19:42
Hm, I'm not able to reproduce this. Can you share a screenshot of what it looks like?

If your issue is that the color is simply black, that's actually a bug and will be fixed in the next version.

**Comment by 9kag** [comment] 2020-03-23 22:22
Here are some pictures to better explain.

**Comment by NoisyFlake** [comment] 2020-03-24 10:49
You didn't post any images.

**Comment by 9kag** [comment] 2020-03-24 13:13
![C39CF759-CF40-49F2-B3BF-59ACCD5DD6FA](https://user-images.githubusercontent.com/62510444/77429207-ad27ea00-6daf-11ea-8b05-e6495b87cfb9.png)
![6528990D-B257-42AE-8DCF-DF34052B7BC7](https://user-images.githubusercontent.com/62510444/77429221-b0bb7100-6daf-11ea-9e79-cd02028508fc.png)
![45D4C4FA-C932-485B-B8A2-AB6EE9A5EFD2](https://user-images.githubusercontent.com/62510444/77429223-b1540780-6daf-11ea-8bea-e72ca30b8993.png)

**Comment by NoisyFlake** [comment] 2020-03-24 14:03
I understand. This is partly Prysms fault, because it uses the Skip button as a Play button when no media is playing. I'll try to fix it in the next version nevertheless.

**Comment by 9kag** [comment] 2020-03-24 14:12
Sounds great! It use to work fine before, not sure why it changed abruptly

**Comment by NoisyFlake** [comment] 2020-03-27 11:41
Fixed in v1.2.3

**Closed by NoisyFlake** 2020-03-27 11:41 UTC
Labels: question
