### ISSUE TITLE
Only enabled toggles show as glyphs in connectivity

### ISSUE THREAD

**Issue by gerbil-snot** [NoisyFlake/MagmaEvo-support#23] opened 2020-02-20 17:28 UTC
**Describe the bug**
When enabling Glyph Only in connectivity, only toggles that are enabled show as glyphs, if they’re not on they show up in the default way. 

**To Reproduce**
1. Go to 'Magma Evo settings > Enable Glyph Only > Respring'
2. Pull the CC down
3. See error

**Expected behavior**
All connectivity modules should show as glyphs

**Screenshots**
![21745FBD-6695-449E-8D8B-95356225C93C](https://user-images.githubusercontent.com/29874563/74961481-c403a700-53d3-11ea-9b2a-032c109fd511.jpeg)

**iOS Version:**
iOS 13.3

**Device:**
iPhone Xs Max 

**Tweak list:**
https://pastebin.com/bY2WGZgW

**Comment by NoisyFlake** [comment] 2020-02-20 20:57
Duplicate of #10

**Closed by NoisyFlake** 2020-02-20 20:57 UTC
