### ISSUE TITLE
Volume/brightness sliders disappear

### ISSUE THREAD

**Issue by royorbs3** [NoisyFlake/MagmaEvo-support#14] opened 2020-01-27 01:44 UTC
**Describe the bug**
Setting color for volume and brightness removes all color or takes the color of the background - I had my bg set to black. 
**To Reproduce**
Change the color of the sliders. Observe. 

**Expected behavior**
For it to change the color as expected. 

**Screenshots**

**iOS Version:**
13.2.2
**Device:**
X
**Tweak list:**
Betterccicons , sugarcane13 - only ones that might affect this

**Additional context**

**Comment by NoisyFlake** [comment] 2020-01-27 09:16
Duplicate of #1, #2 and #11

**Closed by NoisyFlake** 2020-01-27 09:16 UTC
