### ISSUE TITLE
Sliders not showing colors

### ISSUE THREAD

**Issue by raf1dd** [NoisyFlake/MagmaEvo-support#2] opened 2020-01-14 18:18 UTC
**Describe the bug**
Brightness and volume sliders won’t show colors please refer to the screenshot attached below for better understanding.

**To Reproduce**
just try changing the volume and brightness slider to any color 

**Expected behavior**
Volume and brightness sliders to show the colors 😥

**Screenshots**
https://imgur.com/a/WD01d4j

**iOS Version: 13.2.2**

**Device: iPhone X**

**Tweak list: https://pastebin.com/2Mjy4FLQ**

**Additional context**
I own both magma pro and evo and both of them always had the same bug since ios 13 but magma pro worked flawlessly back in ios 12 so i am assuming it has to do something with ios 13 because it works on my iphone 6s test device which is on ios 13 as well

**Comment by NoisyFlake** [comment] 2020-01-14 18:20
Duplicate of #1

**Closed by NoisyFlake** 2020-01-14 18:20 UTC
Labels: duplicate
