### ISSUE TITLE
Slider background issue and glyph color issue

### ISSUE THREAD

**Issue by deucetresthugz** [NoisyFlake/MagmaEvo-support#1] opened 2020-01-14 18:02 UTC
**Describe the bug**
On my iphone X 13.3, whenever I set my background to transparent, the volume slider background stays dark and everything else is transparent as expected. Both sliders (brightness and volume) colors are set exactly the same. Also, the background fill colors I set for both sliders aren’t working regardless of what I set the Control Center background color to be (transparent, white, black, etc..). Lastly, there’s an issue with glyphs not coloring to what I had set the global enable/disable colors as (Notice the rotation lock, UI, and device lock glyph colors

**To Reproduce Volume slider background issue**
1. Go to Miscellaneous 
2. Click on Background color
3. Set the color to transparent (all sliders to the left). Respring 

**Steps to reproduce both slider’s background fill behavior not working**
1. Go to Sliders options 
2. Change slider backgrounds to whatever color. Respring 
3. See error 

**Expected behavior**
The volume background to match the rest of the CC and for the slider’s fill behavior to color as what was set via options above.

**Screenshots**
![BFBEEC03-FCDE-4D26-AAEF-3676034670A2](https://user-images.githubusercontent.com/42386067/72367929-1235d400-36cb-11ea-8553-60dcac07a9e9.png)

**iOS Version:** 13.3

**Device:** iphone X

**Tweak list:**
**CC related tweaks:**
Togglow, CCModules,CCSupport, CCLinker, PowerModule, BetterCCXI (including BetterCCXI weather module), CCsupport, Sugarcane (v 1.2-3 debug), and FlipConvert

Rest of my tweaks: https://pastebin.com/RG1nLGpq
**Additional context**
Regarding the background over hang of the weather module and the media player; is this something that could be related to or fixed with Magma Evo or Magma Pro? I have changed my corner radius’ to pretty much both ends of the spectrum with togglow but no matter what ilI set it to, that overhang is still present. I’m using the same presets with magma pro and togglow as I did when it was working (perfectly aligned) when on ios 11 & 12 with only these two tweaks and the same cc tweaks as I’m currently running. Here are pictures to show what I’m referring to;
![AE05B1C4-6EB9-4983-A155-FFA1E3A638DE](https://user-images.githubusercontent.com/42386067/72369097-63df5e00-36cd-11ea-8bb3-3623a6d01a33.jpeg)
![FAE64AF1-1FA2-4946-A1E3-29F6DBA023B6](https://user-images.githubusercontent.com/42386067/72369098-63df5e00-36cd-11ea-9584-1361fdfdc34d.jpeg)

**Comment by NoisyFlake** [comment] 2020-01-14 18:18
Your CC is tweaked quite a lot. Do any of these bugs appear also with no other tweaks enabled? If yes, please provide a screenshot of this, just so I can be sure that it's not another tweak conflicting.

**Comment by raf1dd** [comment] 2020-01-14 18:23
Sorry for the making a post without seeing one exists but yet i am having the same issue and my cc is not tweaked at all matter fact i have been having this issue since ios 13 with magma pro.

**Comment by deucetresthugz** [comment] 2020-01-14 18:42
> Your CC is tweaked quite a lot. Do any of these bugs appear also with no other tweaks enabled? If yes, please provide a screenshot of this, just so I can be sure that it's not another tweak conflicting.
> 
> Why would you want to color your background transparent, isn't that the same as stock iOS?
> 
> Also, if anyone else experiences this problem, please comment with your iOS version, device and tweak list.

This is will all other tweaks disabled except for magma evo. The glyph color for the screen rotation toggle is still discolored and the slider fill backgrounds don’t work either
![0D8E8530-24A9-48C0-9575-44F13142F041](https://user-images.githubusercontent.com/42386067/72372083-b4f25080-36d3-11ea-9125-b3f16207a97e.png)

**Comment by NoisyFlake** [comment] 2020-01-14 18:50
This doesn't look like you disabled all other tweaks. The status bar is still themed in a way that Magma Evo can't do and your battery doesn't look like stock either.

**Comment by raf1dd** [comment] 2020-01-14 18:55
![FE918464-BB41-4D05-B271-5DFF556A2CAD](https://user-images.githubusercontent.com/22422727/72372967-65ad1f80-36d5-11ea-8daf-f08a5eae557a.png)
Only the sliders themed everything else default

**Comment by deucetresthugz** [comment] 2020-01-14 19:05
> Your CC is tweaked quite a lot. Do any of these bugs appear also with no other tweaks enabled? If yes, please provide a screenshot of this, just so I can be sure that it's not another tweak conflicting.
> 
> Why would you want to color your background transparent, isn't that the same as stock iOS?
> 
> Also, if anyone else experiences this problem, please comment with your iOS version, device and tweak list.

This is will all other tweaks disabled except for magma evo. The glyph color for the screen rotation toggle is still discolored and the slider fill backgrounds don’t work either

**Comment by deucetresthugz** [comment] 2020-01-14 19:07
Sorry my fault. Here is everything disabled (including statusbar stuff) but still having the exact same issue

![F0F9232D-A654-4046-B5A7-ADA17E1A34DE](https://user-images.githubusercontent.com/42386067/72373881-2aabeb80-36d7-11ea-9868-e7c88605aada.png)

**Comment by deucetresthugz** [comment] 2020-01-14 19:15
sorry, I accidentally closed it. still a newbie with github

**Comment by NoisyFlake** [comment] 2020-01-14 19:17
There is still a custom font enabled. How can I trust that you disable **ALL** other tweaks when you failed to do so twice already? This is not helping.

**Comment by NoisyFlake** [comment] 2020-01-14 20:04
Oh my god, I think I might just have finally found it! Can you go to Settings -> Accessibility -> Display & Text Size and see if "Reduce transparency" is turned on? If yes, please turn it off and perform a respring. Let me know if that fixed it for you.

**Comment by raf1dd** [comment] 2020-01-14 20:06
Its been turned off for me since a long time ago

**Comment by NoisyFlake** [comment] 2020-01-14 20:12
Too bad. For the first time I was able to reproduce this issue, but only with **Reduce transparency** enabled. As soon as I turned it off again, everything was working again. Maybe there is a similar setting enabled on your phone that might cause this?

**Comment by raf1dd** [comment] 2020-01-14 20:15
OMG DISABLING REDUCE MOTION WORKED!!!

**Comment by NoisyFlake** [comment] 2020-01-14 20:18
Thank god, this bug was driving me crazy. @deucetresthugz Can you confirm that disabling Reduce motion / Reduce transparency fixed it for you?

**Comment by raf1dd** [comment] 2020-01-14 20:21
man it was driving me crazy too always wanted this to work since ios 13 jb release but finally man.

Thanks a lot for your fast continuous support and for developing such amazing tweak. 💯 

My reddit username is: raf1dd

**Comment by raf1dd** [comment] 2020-01-14 20:29
![D59827EB-B972-487B-A7E9-08D9C75A0AD2](https://user-images.githubusercontent.com/22422727/72380055-9c3d6700-36e2-11ea-81db-a586ce764ccb.png)
Another bug where the brightness slider background is not black like the volume slider :/

**Comment by NoisyFlake** [comment] 2020-01-14 20:35
What is the expected behavior? The brightness or the volume slider? Do you have "remove container background" turned on or off? And does that also happen when you're not connected to AirPods?

**Comment by raf1dd** [comment] 2020-01-14 20:44
Sorry ignore that not related to your tweak this bug always existed for me but i just noticed now and i have no clue what tweak is causing it haha thanks anyways

**Comment by NoisyFlake** [comment] 2020-01-14 20:59
Glad to hear that :)

**Comment by NoisyFlake** [comment] 2020-01-14 22:32
Closing this as it seems to be fixed for everyone now. 

**Solution:** Make sure that Reduce motion and Reduce transparency are disabled in your Accessibility settings. After disabling them, perform a respring.

**Closed by NoisyFlake** 2020-01-14 22:32 UTC
Labels: configuration issue

**Comment by deucetresthugz** [comment] 2020-01-14 22:41
> Oh my god, I think I might just have finally found it! Can you go to Settings -> Accessibility -> Display & Text Size and see if "Reduce transparency" is turned on? If yes, please turn it off and perform a respring. Let me know if that fixed it for you.

I keep it disabled bc I use transparency wallet

**Comment by deucetresthugz** [comment] 2020-01-14 22:55
it’s not completely solved bc the glyph color issue is still present. I’ve been playing around with the colors with tweaks disabled and both Transparency and reduce motion disabled and the colors still aren’t lining up 
![84F9A909-75F4-410C-ACB4-919BEB9055F4](https://user-images.githubusercontent.com/42386067/72389711-0f50d880-36f7-11ea-9650-e17fbefdf430.png)

**Comment by NoisyFlake** [comment] 2020-01-14 23:06
What exactly is the problem that remains? The screenshot looks fine to me.

**Comment by deucetresthugz** [comment] 2020-01-14 23:24
TWFnbWFFdm86PD94bWwgdmVyc2lvbj0iMS4wIiBlbmNvZGluZz0iVVRGLTgiPz4KPCFET0NUWVBFIHBsaXN0IFBVQkxJQyAiLS8vQXBwbGUvL0RURCBQTElTVCAxLjAvL0VOIiAiaHR0cDovL3d3dy5hcHBsZS5jb20vRFREcy9Qcm9wZXJ0eUxpc3QtMS4wLmR0ZCI+CjxwbGlzdCB2ZXJzaW9uPSIxLjAiPgo8ZGljdD4KCTxrZXk+Q0NVSUNvbm5lY3Rpdml0eUFpckRyb3BWaWV3Q29udHJvbGxlckRpc2FibGVkPC9rZXk+Cgk8c3RyaW5nPiM2QTAwRkY6MS4wMDwvc3RyaW5nPgoJPGtleT5DQ1VJQ29ubmVjdGl2aXR5QWlyRHJvcFZpZXdDb250cm9sbGVyRW5hYmxlZDwva2V5PgoJPHN0cmluZz4jMDBGRkE5OjEuMDA8L3N0cmluZz4KCTxrZXk+Q0NVSUNvbm5lY3Rpdml0eUFpcnBsYW5lVmlld0NvbnRyb2xsZXJEaXNhYmxlZDwva2V5PgoJPHN0cmluZz4jNkEwMEZGOjEuMDA8L3N0cmluZz4KCTxrZXk+Q0NVSUNvbm5lY3Rpdml0eUFpcnBsYW5lVmlld0NvbnRyb2xsZXJFbmFibGVkPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5DQ1VJQ29ubmVjdGl2aXR5Qmx1ZXRvb3RoVmlld0NvbnRyb2xsZXJEaXNhYmxlZDwva2V5PgoJPHN0cmluZz4jNkEwMEZGOjEuMDA8L3N0cmluZz4KCTxrZXk+Q0NVSUNvbm5lY3Rpdml0eUJsdWV0b290aFZpZXdDb250cm9sbGVyRW5hYmxlZDwva2V5PgoJPHN0cmluZz4jMDBGRkE5OjEuMDA8L3N0cmluZz4KCTxrZXk+Q0NVSUNvbm5lY3Rpdml0eUNlbGx1bGFyRGF0YVZpZXdDb250cm9sbGVyRGlzYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzZBMDBGRjoxLjAwPC9zdHJpbmc+Cgk8a2V5PkNDVUlDb25uZWN0aXZpdHlDZWxsdWxhckRhdGFWaWV3Q29udHJvbGxlckVuYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzAwRkZBOToxLjAwPC9zdHJpbmc+Cgk8a2V5PkNDVUlDb25uZWN0aXZpdHlIb3RzcG90Vmlld0NvbnRyb2xsZXJEaXNhYmxlZDwva2V5PgoJPHN0cmluZz4jNkEwMEZGOjEuMDA8L3N0cmluZz4KCTxrZXk+Q0NVSUNvbm5lY3Rpdml0eUhvdHNwb3RWaWV3Q29udHJvbGxlckVuYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzAwRkZBOToxLjAwPC9zdHJpbmc+Cgk8a2V5PkNDVUlDb25uZWN0aXZpdHlXaWZpVmlld0NvbnRyb2xsZXJEaXNhYmxlZDwva2V5PgoJPHN0cmluZz4jNkEwMEZGOjEuMDA8L3N0cmluZz4KCTxrZXk+Q0NVSUNvbm5lY3Rpdml0eVdpZmlWaWV3Q29udHJvbGxlckVuYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzAwRkZBOToxLjAwPC9zdHJpbmc+Cgk8a2V5PkxvY2tCdXR0b25Db250cm9sbGVyPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5Qb3dlckRvd25CdXR0b25Db250cm9sbGVyPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5SZWJvb3RCdXR0b25Db250cm9sbGVyPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5SZXNwcmluZ0J1dHRvbkNvbnRyb2xsZXI8L2tleT4KCTxzdHJpbmc+IzAwRkZBOToxLjAwPC9zdHJpbmc+Cgk8a2V5PlNhZmVtb2RlQnV0dG9uQ29udHJvbGxlcjwva2V5PgoJPHN0cmluZz4jMDBGRkE5OjEuMDA8L3N0cmluZz4KCTxrZXk+VUlDYWNoZUJ1dHRvbkNvbnRyb2xsZXI8L2tleT4KCTxzdHJpbmc+IzAwRkZBOToxLjAwPC9zdHJpbmc+Cgk8a2V5PmNvbS5hcHBsZS5jb250cm9sLWNlbnRlci5DYWxjdWxhdG9yTW9kdWxlRGlzYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzZBMDBGRjoxLjAwPC9zdHJpbmc+Cgk8a2V5PmNvbS5hcHBsZS5jb250cm9sLWNlbnRlci5DYWxjdWxhdG9yTW9kdWxlRW5hYmxlZDwva2V5PgoJPHN0cmluZz4jMDBGRkE5OjEuMDA8L3N0cmluZz4KCTxrZXk+Y29tLmFwcGxlLmNvbnRyb2wtY2VudGVyLkNhbWVyYU1vZHVsZURpc2FibGVkPC9rZXk+Cgk8c3RyaW5nPiM2QTAwRkY6MS4wMDwvc3RyaW5nPgoJPGtleT5jb20uYXBwbGUuY29udHJvbC1jZW50ZXIuQ2FtZXJhTW9kdWxlRW5hYmxlZDwva2V5PgoJPHN0cmluZz4jMDBGRkE5OjEuMDA8L3N0cmluZz4KCTxrZXk+Y29tLmFwcGxlLmNvbnRyb2wtY2VudGVyLkZsYXNobGlnaHRNb2R1bGVEaXNhYmxlZDwva2V5PgoJPHN0cmluZz4jNkEwMEZGOjEuMDA8L3N0cmluZz4KCTxrZXk+Y29tLmFwcGxlLmNvbnRyb2wtY2VudGVyLkZsYXNobGlnaHRNb2R1bGVFbmFibGVkPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5jb20uYXBwbGUuY29udHJvbC1jZW50ZXIuT3JpZW50YXRpb25Mb2NrTW9kdWxlRGlzYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzZBMDBGRjoxLjAwPC9zdHJpbmc+Cgk8a2V5PmNvbS5hcHBsZS5jb250cm9sLWNlbnRlci5PcmllbnRhdGlvbkxvY2tNb2R1bGVFbmFibGVkPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5jb20uYXBwbGUubW9iaWxldGltZXIuY29udHJvbGNlbnRlci50aW1lckRpc2FibGVkPC9rZXk+Cgk8c3RyaW5nPiM2QTAwRkY6MS4wMDwvc3RyaW5nPgoJPGtleT5jb20uYXBwbGUubW9iaWxldGltZXIuY29udHJvbGNlbnRlci50aW1lckVuYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzAwRkZBOToxLjAwPC9zdHJpbmc+Cgk8a2V5PmNvbS5leGlsZTkwLmljbGVhbmVyLmZsaXBzd2l0Y2guY2xlYW5ub3BvcHVwRGlzYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzZBMDBGRjoxLjAwPC9zdHJpbmc+Cgk8a2V5PmNvbS5leGlsZTkwLmljbGVhbmVyLmZsaXBzd2l0Y2guY2xlYW5ub3BvcHVwRW5hYmxlZDwva2V5PgoJPHN0cmluZz4jMDBGRkE5OjEuMDA8L3N0cmluZz4KCTxrZXk+Y29tLmphaWxicmVhazM2NS5jb250cm9sLWNlbnRlci5MRFJlc3RhcnRNb2R1bGVEaXNhYmxlZDwva2V5PgoJPHN0cmluZz4jNkEwMEZGOjEuMDA8L3N0cmluZz4KCTxrZXk+Y29tLmphaWxicmVhazM2NS5jb250cm9sLWNlbnRlci5MRFJlc3RhcnRNb2R1bGVFbmFibGVkPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5jb20uamFpbGJyZWFrMzY1LmNvbnRyb2wtY2VudGVyLk5ld1Rlcm0yTW9kdWxlRGlzYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzZBMDBGRjoxLjAwPC9zdHJpbmc+Cgk8a2V5PmNvbS5qYWlsYnJlYWszNjUuY29udHJvbC1jZW50ZXIuTmV3VGVybTJNb2R1bGVFbmFibGVkPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5jb20uamFpbGJyZWFrMzY1LmNvbnRyb2wtY2VudGVyLlJlc3ByaW5nTW9kdWxlRGlzYWJsZWQ8L2tleT4KCTxzdHJpbmc+IzZBMDBGRjoxLjAwPC9zdHJpbmc+Cgk8a2V5PmNvbS5qYWlsYnJlYWszNjUuY29udHJvbC1jZW50ZXIuUmVzcHJpbmdNb2R1bGVFbmFibGVkPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5jb25uZWN0aXZpdHlIaWRlQ29udGFpbmVyPC9rZXk+Cgk8ZmFsc2UvPgoJPGtleT5jb25uZWN0aXZpdHlNb2RlRGlzYWJsZWQ8L2tleT4KCTxzdHJpbmc+Z2x5cGhPbmx5PC9zdHJpbmc+Cgk8a2V5PmNvbm5lY3Rpdml0eU1vZGVFbmFibGVkPC9rZXk+Cgk8c3RyaW5nPmdseXBoT25seTwvc3RyaW5nPgoJPGtleT5jb25uZWN0aXZpdHlQb3NpdGlvbjA8L2tleT4KCTxzdHJpbmc+Q0NVSUNvbm5lY3Rpdml0eUFpcnBsYW5lVmlld0NvbnRyb2xsZXI8L3N0cmluZz4KCTxrZXk+Y29ubmVjdGl2aXR5UG9zaXRpb24xPC9rZXk+Cgk8c3RyaW5nPkNDVUlDb25uZWN0aXZpdHlDZWxsdWxhckRhdGFWaWV3Q29udHJvbGxlcjwvc3RyaW5nPgoJPGtleT5jb25uZWN0aXZpdHlQb3NpdGlvbjI8L2tleT4KCTxzdHJpbmc+Q0NVSUNvbm5lY3Rpdml0eVdpZmlWaWV3Q29udHJvbGxlcjwvc3RyaW5nPgoJPGtleT5jb25uZWN0aXZpdHlQb3NpdGlvbjM8L2tleT4KCTxzdHJpbmc+Q0NVSUNvbm5lY3Rpdml0eUJsdWV0b290aFZpZXdDb250cm9sbGVyPC9zdHJpbmc+Cgk8a2V5PmNvbm5lY3Rpdml0eVBvc2l0aW9uNDwva2V5PgoJPHN0cmluZz5DQ1VJQ29ubmVjdGl2aXR5QWlyRHJvcFZpZXdDb250cm9sbGVyPC9zdHJpbmc+Cgk8a2V5PmNvbm5lY3Rpdml0eVBvc2l0aW9uNTwva2V5PgoJPHN0cmluZz5DQ1VJQ29ubmVjdGl2aXR5SG90c3BvdFZpZXdDb250cm9sbGVyPC9zdHJpbmc+Cgk8a2V5PmVuYWJsZWQ8L2tleT4KCTx0cnVlLz4KCTxrZXk+bWVkaWFDb250cm9sc0NvbG9yTG9ja3NjcmVlbjwva2V5PgoJPHRydWUvPgoJPGtleT5tZWRpYUNvbnRyb2xzSGlkZUNvbnRhaW5lcjwva2V5PgoJPGZhbHNlLz4KCTxrZXk+bWVkaWFDb250cm9sc0xlZnRCdXR0b248L2tleT4KCTxzdHJpbmc+I0RFRkYwMDoxLjAwPC9zdHJpbmc+Cgk8a2V5Pm1lZGlhQ29udHJvbHNNaWRkbGVCdXR0b248L2tleT4KCTxzdHJpbmc+IzBGMDBGRjoxLjAwPC9zdHJpbmc+Cgk8a2V5Pm1lZGlhQ29udHJvbHNQcmltYXJ5TGFiZWw8L2tleT4KCTxzdHJpbmc+I0ZGMDBCNToxLjAwPC9zdHJpbmc+Cgk8a2V5Pm1lZGlhQ29udHJvbHNSaWdodEJ1dHRvbjwva2V5PgoJPHN0cmluZz4jREVGRjAwOjEuMDA8L3N0cmluZz4KCTxrZXk+bWVkaWFDb250cm9sc1NlY29uZGFyeUxhYmVsPC9rZXk+Cgk8c3RyaW5nPiMwMEZGQTk6MS4wMDwvc3RyaW5nPgoJPGtleT5tZWRpYUNvbnRyb2xzU2xpZGVyPC9rZXk+Cgk8c3RyaW5nPiNGRjAwQjY6MS4wMDwvc3RyaW5nPgoJPGtleT5taXNjTWFpbkJhY2tncm91bmQ8L2tleT4KCTxzdHJpbmc+I0ZGRkVGRToxLjAwPC9zdHJpbmc+Cgk8a2V5Pm1pc2NTdGF0dXNCYXJDb2xvcjwva2V5PgoJPHN0cmluZz4jMDBGRkE5OjEuMDA8L3N0cmluZz4KCTxrZXk+bWlzY1N0YXR1c0JhckhpZGU8L2tleT4KCTxmYWxzZS8+Cgk8a2V5PnBvd2VyTW9kdWxlSGlkZUJhY2tncm91bmQ8L2tleT4KCTx0cnVlLz4KCTxrZXk+cG93ZXJNb2R1bGVIaWRlQ29udGFpbmVyPC9rZXk+Cgk8dHJ1ZS8+Cgk8a2V5PnNsaWRlcnNCcmlnaHRuZXNzQmFja2dyb3VuZDwva2V5PgoJPHN0cmluZz4jNkEwMEZGOjEuMDA8L3N0cmluZz4KCTxrZXk+c2xpZGVyc0JyaWdodG5lc3NHbHlwaDwva2V5PgoJPHN0cmluZz4jMDBGRkE5OjEuMDA8L3N0cmluZz4KCTxrZXk+c2xpZGVyc0hpZGVDb250YWluZXI8L2tleT4KCTxmYWxzZS8+Cgk8a2V5PnNsaWRlcnNWb2x1bWVCYWNrZ3JvdW5kPC9rZXk+Cgk8c3RyaW5nPiM2QTAwRkY6MS4wMDwvc3RyaW5nPgoJPGtleT5zbGlkZXJzVm9sdW1lR2x5cGg8L2tleT4KCTxzdHJpbmc+IzAwRkZBOToxLjAwPC9zdHJpbmc+Cgk8a2V5PnRvZ2dsZXNIaWRlQ29udGFpbmVyPC9rZXk+Cgk8ZmFsc2UvPgoJPGtleT50b2dnbGVzT3ZlcmxheU1vZGU8L2tleT4KCTxzdHJpbmc+cmVndWxhcjwvc3RyaW5nPgo8L2RpY3Q+CjwvcGxpc3Q+Cg==

**Comment by deucetresthugz** [comment] 2020-01-14 23:30
https://pastebin.com/tbFCAaBg

**Comment by deucetresthugz** [comment] 2020-01-14 23:51
Here’s what everything looked like when using with magma pro and togglow back on ios 12 that i was referring to in my op. I guess I bought magma evo thinking it was an updated version of magma pro for ios 13
![0BE76193-5EBD-4B1F-B982-610A9CACA10C](https://user-images.githubusercontent.com/42386067/72392759-d288df80-36fe-11ea-99bb-a04d70e2d47d.png)

**Comment by deucetresthugz** [comment] 2020-01-15 04:27
ere’s what everything looked like when using with magma pro and togglow back on ios 12 that i was referring to in my op. I guess I bought magma evo thinking it was an updated version of magma pro for ios 13
![007C79E4-DD3C-40BE-9299-5B91EFA97941](https://user-images.githubusercontent.com/42386067/72392976-74103100-36ff-11ea-9edf-7b185b76d352.png)

**Comment by NoisyFlake** [comment] 2020-01-15 08:29
From the preset it looks like you don't have any color configured for the UICache and Lock Screen Button. As I said, please check that you have colors configured for those toggles.
